### ISSUE TITLE
Server stop

### ISSUE THREAD

**Issue by MrSmileCH** [KairusDarkSeeker/ProxyFirewall#1]
Every time a player enters with a vpn or proxy the server stops or restarts automatically if you are in host, any solution?
Note: do not throw any errors in console!

**Comment by KairusDarkSeeker** [comment]
I don't know, it may be a bug

**Comment by KairusDarkSeeker** [comment]
@MrSmileCH Try using [PMMP](/pmmp/PocketMine-MP)
